# General description


This repository contains the codes for the study 'Seroprevalences of human herpesviruses in France, 2018-2022: a multilevel regression and poststratification approach'. 

Paywall paper available: http://dx.doi.org/10.1080/23744235.2024.2365906

Preprint: posted soon on HAL (https://hal.science/)

# .bib entry:

@article{Supplisson2024,
  title = {Seroprevalence of human herpes viruses in France,  2018–2022: a multilevel regression and poststratification approach},
  volume = {56},
  ISSN = {2374-4243},
  url = {http://dx.doi.org/10.1080/23744235.2024.2365906},
  DOI = {10.1080/23744235.2024.2365906},
  number = {11},
  journal = {Infectious Diseases},
  publisher = {Informa UK Limited},
  author = {Supplisson,  Olivier and Visseaux,  Benoit and Haim-Boukobza,  Stéphanie and Boutolleau,  David and Alizon,  Samuel and Burrel,  Sonia and Sofonea,  Mircea T.},
  year = {2024},
  month = jul,
  pages = {931–945}
}


# Funding

* OS (1st author) is funded by a Ph.D. grant from the ANRS|Maladies infectieuses émergentes (grant number 22485).

# Data sharing

Important: Data cannot be shared due to legal constraints associated with using the French reference methodology MR-004. 


# Acknowledgements

We are grateful to the genotoul bioinformatics platform Toulouse Occitanie (Bioinfo Genotoul, https://doi.org/10.15454/1.5572369328961167E12) for providing help and computing and storage resources.

The authors acknowledge the  ISO 9001 certified IRD i-Trop HPC (South Green Platform) at IRD montpellier for providing HPC resources that have contributed to the research results reported within this paper. https://bioinfo.ird.fr/-http://www.southgreen.fr

We acknowledge Bioclust, the computing cluster of PB-IBENS (LABEX MEMOLIFE members) for providing storage resources. https://www.ibens.bio.ens.psl.eu/spip.php?rubrique55#bioclust
